server:
  port: 8000

spring:
  application:
    name: currency-exchange

  config:
    activate:
      on-profile:

    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      profile: dev

  datasource:
    username: root
    password: Br00k51d3
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/currency_exchange

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true

